#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : jsonlines
Version  : 2.0.0
Release  : 18
URL      : https://files.pythonhosted.org/packages/bf/40/a1b1810a09e3e85567c17831fcc2fc8e48ad9a1d3b02e8be940c43b908a8/jsonlines-2.0.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/bf/40/a1b1810a09e3e85567c17831fcc2fc8e48ad9a1d3b02e8be940c43b908a8/jsonlines-2.0.0.tar.gz
Summary  : Library with helpers for the jsonlines file format
Group    : Development/Tools
License  : BSD-3-Clause
Requires: jsonlines-license = %{version}-%{release}
Requires: jsonlines-python = %{version}-%{release}
Requires: jsonlines-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
.. image:: https://travis-ci.org/wbolster/jsonlines.svg?branch=master
:target: https://travis-ci.org/wbolster/jsonlines

%package license
Summary: license components for the jsonlines package.
Group: Default

%description license
license components for the jsonlines package.


%package python
Summary: python components for the jsonlines package.
Group: Default
Requires: jsonlines-python3 = %{version}-%{release}

%description python
python components for the jsonlines package.


%package python3
Summary: python3 components for the jsonlines package.
Group: Default
Requires: python3-core
Provides: pypi(jsonlines)

%description python3
python3 components for the jsonlines package.


%prep
%setup -q -n jsonlines-2.0.0
cd %{_builddir}/jsonlines-2.0.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1609792874
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/jsonlines
cp %{_builddir}/jsonlines-2.0.0/LICENSE.rst %{buildroot}/usr/share/package-licenses/jsonlines/7eb5eead6a74774b171f088b8421ee02e94acb0b
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/jsonlines/7eb5eead6a74774b171f088b8421ee02e94acb0b

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
