#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : jsonlines
Version  : 1.2.0
Release  : 4
URL      : https://files.pythonhosted.org/packages/90/cd/0beacbcfdf9b3af9e7c615cb3dba7ec4be1030d4b283e3c9717e3fd9af3c/jsonlines-1.2.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/90/cd/0beacbcfdf9b3af9e7c615cb3dba7ec4be1030d4b283e3c9717e3fd9af3c/jsonlines-1.2.0.tar.gz
Summary  : Library with helpers for the jsonlines file format
Group    : Development/Tools
License  : BSD-3-Clause
Requires: jsonlines-license = %{version}-%{release}
Requires: jsonlines-python = %{version}-%{release}
Requires: jsonlines-python3 = %{version}-%{release}
Requires: six
BuildRequires : buildreq-distutils3
BuildRequires : six

%description
=========
jsonlines
=========

``jsonlines`` is a Python library to simplify working with jsonlines_
and ndjson_ data.

.. _jsonlines: http://jsonlines.org/
.. _ndjson: http://ndjson.org/

* Documentation: https://jsonlines.readthedocs.io/

* Python Package Index (PyPI): https://pypi.python.org/pypi/jsonlines/

* Source code and issue tracker: https://github.com/wbolster/jsonlines

.. image:: https://travis-ci.org/wbolster/jsonlines.svg?branch=master
   :target: https://travis-ci.org/wbolster/jsonlines

%package license
Summary: license components for the jsonlines package.
Group: Default

%description license
license components for the jsonlines package.


%package python
Summary: python components for the jsonlines package.
Group: Default
Requires: jsonlines-python3 = %{version}-%{release}

%description python
python components for the jsonlines package.


%package python3
Summary: python3 components for the jsonlines package.
Group: Default
Requires: python3-core
Provides: pypi(jsonlines)

%description python3
python3 components for the jsonlines package.


%prep
%setup -q -n jsonlines-1.2.0
cd %{_builddir}/jsonlines-1.2.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1583161654
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/jsonlines
cp %{_builddir}/jsonlines-1.2.0/LICENSE.rst %{buildroot}/usr/share/package-licenses/jsonlines/7eb5eead6a74774b171f088b8421ee02e94acb0b
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/jsonlines/7eb5eead6a74774b171f088b8421ee02e94acb0b

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
